name: pcc
version: "3.0.0"
description: "Parallel Claude Coordinator v3.0 - Orchestrate complex tasks with dual-mode parallel agent exploration and implementation"
author: "Kasempiternal"
repository: "https://github.com/Kasempiternal/Claude-Agent-System"
